[project]
name = "peakoscope-demo"
version = "0.1.0"
description = "Demo of the peakoscope package"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
  { name="Eivind Tøstesen", email="contact@tostesen.no" },
]
